#!/bin/bash

color(){
	case "${1}" in
		black) local COLOR="\e[30m" ;;
		red) local COLOR="\e[31m" ;;
		green) local COLOR="\e[32m" ;;
		yellow) local COLOR="\e[33m" ;;
		blue) local COLOR="\e[34m" ;;
		magenta) local COLOR="\e[35m" ;;
		cyan) local COLOR="\e[36m" ;;
		white) local COLOR="\e[37m" ;;
		*) local COLOR="\e[37m" ;;
	esac
    local RESET="\e[39m"
	printf "${COLOR}${2}${RESET}\n"
}

message(){
	case "${1}" in
	success)
		echo "[ $(color green OK) ] ${2}"
	;;
	info)
		echo "[ $(color blue INFO) ] ${2}"
	;;
	user)
		echo "[ $(color yellow ??) ] ${2}"
	;;
	warn)
		echo "[ $(color yellow WARN) ] ${2}"
	;;
	error)
		echo "[ $(color red ERROR) ] ${2}"
	;;
	fail)
		echo "[ $(color red FAIL) ] ${2}"
	;;
	*)
		echo "Incorrect Argument"
	;;
	esac
}

abort(){
	message error "${1}"
	exit 1
}

has(){
	type ${1} >/dev/null 2>&1 || abort "Command not found: ${1}"
}

USERNAME="sho"

[ "$(whoami)" == "root" ] || abort "Need to be root"
